name: "AetherBuild"
description: "An Automated Pipelline WHich Builds all the applications, releases them and updates the website + Linkedin Post"

permissions:
  contents: write

on:
    push:
        branches:
            - github-actions

jobs:

  build_init_notification:
    uses: ./.github/workflows/notify-build-init.yml
    secrets: inherit
    
  android:
    needs: build_init_notification
    uses: ./.github/workflows/build-android.yml
    secrets: inherit

  windows:
    needs: build_init_notification
    uses: ./.github/workflows/build-windows.yml

  linux:
    needs: build_init_notification
    uses: ./.github/workflows/build-linux-appimage.yml

  build_summary_notification:
    if: always()
    needs: [android, windows, linux]
    uses: ./.github/workflows/notify-build-summary.yml
    secrets: inherit
    with:
      android_status: ${{ needs.android.result }}
      windows_status: ${{ needs.windows.result }}
      linux_status: ${{ needs.linux.result }}





              





