name: "AethrBuild"
description: "An Automated Pipelline WHich Builds all the applications, releases them and updates the website + Linkedin Post"

permissions:
  contents: write

on:
    workflow_dispatch:

jobs:

  build_init_notification:
    name: Build Init Notification
    uses: ./.github/workflows/notify-build-init.yml
    secrets: inherit
    
  android:
    name: AethrOps Android Build
    needs: build_init_notification
    if: success()
    uses: ./.github/workflows/build-android.yml
    secrets: inherit

  windows:
    name: Aethrops Windows Build
    needs: build_init_notification
    if: success()
    uses: ./.github/workflows/build-windows.yml

  linux:
    name: Aethrops Linux AppImage Build
    needs: build_init_notification
    if: success()
    uses: ./.github/workflows/build-linux-appimage.yml

  build_summary_notification:
    name: Build Summary Notification
    if: always()
    needs: [android, windows, linux]
    uses: ./.github/workflows/notify-build-summary.yml
    secrets: inherit
    with:
      android_status: ${{ needs.android.result }}
      windows_status: ${{ needs.windows.result }}
      linux_status: ${{ needs.linux.result }}

  release:
    name: Github Release
    needs: build_summary_notification
    if: success()
    uses: ./.github/workflows/github-release.yml

  website_update:
    name: Website Update
    needs: release
    if: success()
    uses: ./.github/workflows/website-release.yml
    secrets: inherit

  linkedin_post:
    name: LinkedIn Post
    needs: release
    if: success()
    uses: ./.github/workflows/post-linkedin.yml
    secrets: inherit






              



