name: AethrOps Github Release

on:
    workflow_call:

jobs:
    release: 
      name: Github Release
      runs-on: ubuntu-latest

      env:
        RELEASE_TAG: preview-beta-2
        RELEASE_NAME: "AethrOps Preview Beta 2(CI TEST)"
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Download Android Artifacts
          uses: actions/download-artifact@v4
          with:
            name: AethrOps-android-release
            path: release/android
          
        - name: Download Windows Artifacts
          uses: actions/download-artifact@v4
          with:
            name: AethrOps-windows-build
            path: release/windows
        
        - name: Download Linux Artifacts
          uses: actions/download-artifact@v4
          with:
            name: AethrOps-linux-appimage
            path: release/linux
          
        - name: Create GitHub Release
          uses: softprops/action-gh-release@v2
          with:
            tag_name: ${{ env.RELEASE_TAG }}
            name: ${{ env.RELEASE_NAME }}
            body_path: RELEASE_NOTES.md
            files: |
              release/android/*.apk
              release/windows/*.exe
              release/linux/*.AppImage